### ISSUE TITLE
Wiki page for phase 3

### ISSUE THREAD

**Issue by ibalajiarun** [ECE4574-5574/MobileApp#11]
The assignment page has details on this one

**Comment by cmpadden** [comment]
The Wiki page for 'Scenario i. User of the App adds a new device', has been completed.

**Comment by cmpadden** [comment]
@Brian-Kaplan could you write a brief summary on what APIs are used for 'Scenario iii. User of the App issues the verbal command to make it brighter near me'.

Also, who can write the one for 'Scenario ii. Light is dimmed by a physical light switch'?

**Comment by Brian-Kaplan** [comment]
@cmpadden please take a look at this https://gist.github.com/Brian-Kaplan/21ca711a76a4d4534957

Let me know if I need to be more descriptive

**Comment by cmpadden** [comment]
@Brian-Kaplan Look good to me; I'll go ahead and post it to the Wiki. Only Scenario ii. remains for this issue.
